### ISSUE TITLE
Adding a Bottom Sidebar button with a Custom Layout mode?

### ISSUE THREAD

**Issue by loretoparisi** [erndev/EDSidebar#1]
Is it possible to add a sidebar button using a custom layout and/or custom position ?
What I would like to have is to add a bottom button using the ECSideBarLayoutTop layout mode for all others buttons (like in Twitter for Mac by example).
Any way to do this with the current api ?

**Comment by erndev** [comment]
it's not possible. but i may be i good idea. I will look into it. 
There is another way though. EDSideBar is a regular NSView. You could add that button as a subview, and set it to align to the bottom.

**Comment by loretoparisi** [comment]
Thanks a lot erndev, I'm doing this solution by now and waiting for you update next.
